adding error message for when no launcher command is found

diff --git a/bash/webtap/webtap b/bash/webtap/webtap
--- a/bash/webtap/webtap
+++ b/bash/webtap/webtap
@@ -44,6 +44,9 @@ webtap_launcher(){
 				# on failure, continue to next in list
 			fi
 		done
+	else
+		echo "error: no tapper configured"
+		exit 1
 	fi
 }
 
